version: "3"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_order_app
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#     networks:
#       - microservices-network

# networks:
#   microservices-network:
#     driver: bridge

volumes:
  rabbitmq_data:
    driver: local
