apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: thallavi/notification-service:b324259
          ports:
            - containerPort: 5000
          env:
            - name: SECRET_KEY
              value: "your-secret-key"
