apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: thallavi/order-service:latest
          ports:
            - containerPort: 4000
          env:
            - name: SECRET_KEY
              value: "your-secret-key"
